### ISSUE TITLE
`SES_IMPORT_REJECTED` upon importing viem

### ISSUE THREAD

**Issue by firnprotocol** [MetaMask/snaps#1443]
hi all, SES is rejecting my import of [viem](https://viem.sh/), a simple and minimal ethereum library.

to reproduce:
- clone the [`template-snap-monorepo`](https://github.com/MetaMask/template-snap-monorepohttps://github.com/MetaMask/template-snap-monorepo).
- in that directory, navigate to `/packages/snap/`.
- run `yarn add viem`.
- add the line `import { keccak256 } from 'viem';` right here:
https://github.com/MetaMask/template-snap-monorepo/blob/c0d6591bcf30c2134544db0c88327f94553ffc34/packages/snap/src/index.ts#L2
- run `yarn start` in the top-level directory of the repo.

this will yield:
```
[SyntaxError: Possible import expression rejected at <unknown>:10280. (SES_IMPORT_REJECTED)]
Error during initial build. Error: Snap evaluation error: Process exited with non-zero exit code: 255
    at evalHandler (/Users/firnprotocol/template-snap-monorepo/node_modules/@metamask/snaps-cli/dist/cmds/eval/evalHandler.js:21:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async buildSnap (/Users/firnprotocol/template-snap-monorepo/node_modules/@metamask/snaps-cli/dist/cmds/watch/watchHandler.js:47:17)
```

thanks in advance for your attention.

**Comment by FrederikBolding** [comment]
@firnprotocol It looks like `viem` is using async imports which are currently not supported by default in Snaps. However, you can work around this by transpiling. I was able to get `viem` running with the following steps, let me know if they work out for you:

1. Use `@metamask/snaps-cli` version `"^0.33.1-flask.1"`
2. In `snap.config.js` under `cliOptions` add `transpilationMode: 'localAndDeps'`

**Comment by firnprotocol** [comment]
great; this appears to work; thank you very much.

**Comment by firnprotocol** [comment]
actually, @FrederikBolding, sorry, but could I ask the significance of the `-flask.1` suffix in the version? thanks in advance.

**Comment by FrederikBolding** [comment]
> actually, @FrederikBolding, sorry, but could I ask the significance of the `-flask.1` suffix in the version? thanks in advance.

The platform is currently under audit and for that to happen we've had to have a code-freeze. While the code-freeze is ongoing for the stable version of the Snaps Platform, we've continued to release new updates for the experimental/flask version. These packages are suffixed with `-flask` to prevent any confusion around that. 

Specifically with the CLI however, it shouldn't be a problem for you to use either version. But I knew for a fact that the latest experimental version had some fixes for your exact problems.
