### ISSUE TITLE
npm/yarn create @metamask/snap failed: Init Error: Failed to create template

### ISSUE THREAD

**Issue by Vivomo** [MetaMask/snaps#1577]
When I install @metamask/create-snap, I followed the doc of Metamask snap.
I tried to use this commands, but it all failed and outputed the same error info.
### command
`yarn create @metamask/snap your-snap-name`, `npmcreate @metamask/snap your-snap-name` and `npx @metamask/snap your-snap-name`
### Error info
```
***\node_modules\@metamask\create-snap\dist\cmds\init\initHandler.js:47
        throw new Error('Init Error: Failed to create template.');
              ^

Error: Init Error: Failed to create template.
    at initHandler (****\node_modules\@metamask\create-snap\dist\cmds\init\initHandler.js:47:15)
```
### Error log
```
39 verbose stack Error: command failed
39 verbose stack     at ChildProcess.<anonymous> (****\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:53:27)
39 verbose stack     at ChildProcess.emit (node:events:513:28)
39 verbose stack     at maybeClose (node:internal/child_process:1091:16)
39 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
40 verbose cwd ****
41 verbose Windows_NT 10.0.18362
42 verbose node v18.16.0
43 verbose npm  v9.5.1
44 error code 1
```

I replaced file path with ****.

**Comment by Vivomo** [comment]
I resoved it by clean npm cache

**Comment by paulfears** [comment]
Also breaks on windows if there is a space in the path

**Comment by bin-dogami** [comment]
I hava the same problem. But isn't work for me to clean the npm cache.
