### ISSUE TITLE
Snap installation fails with "Snap tarball exceeds limit of ${TARBALL_SIZE_SAFETY_LIMIT} bytes."

### ISSUE THREAD

**Issue by Montoya** [MetaMask/snaps#1704]
The following snap cannot be installed from npm: https://www.npmjs.com/package/@shapeshiftoss/metamask-snaps

I have confirmed that the same error occurs when trying to load it in the Snaps Simulator: 

```
Error: Snap tarball exceeds limit of 262144000 bytes.
    at s (https://metamask.github.io/snaps/snaps-simulator/staging/vendor/vendor.js:2345:20346)
    at l (https://metamask.github.io/snaps/snaps-simulator/staging/vendor/vendor.js:2345:20657)
    at https://metamask.github.io/snaps/snaps-simulator/staging/main.js:418:243816
    at u.<anonymous> (https://metamask.github.io/snaps/snaps-simulator/staging/main.js:16:44596)
    at o.emit (https://metamask.github.io/snaps/snaps-simulator/staging/main.js:16:113138)
    at F (https://metamask.github.io/snaps/snaps-simulator/staging/main.js:418:21444)
    at C.end (https://metamask.github.io/snaps/snaps-simulator/staging/main.js:418:24329)
    at p.s (https://metamask.github.io/snaps/snaps-simulator/staging/main.js:418:11279)
    at Object.d (https://metamask.github.io/snaps/snaps-simulator/staging/main.js:16:111058)
    at o.emit (https://metamask.github.io/snaps/snaps-simulator/staging/main.js:16:113081)
```

The npm package is 12.3 MB.

**Comment by FrederikBolding** [comment]
Tracked down this bug, it happens when an NPM file in the package has a length of zero bytes. Will provide a fix in the morning.
