### ISSUE TITLE
Error: The method \"wallet_invokeKeyring\" does not exist / is not available

### ISSUE THREAD

**Issue by livingrockrises** [MetaMask/snaps#2146]
Full trace

```
{
  "code": -32601,
  "message": "The method \"wallet_invokeKeyring\" does not exist / is not available.",
  "data": {
    "origin": "http://localhost:4000"
  },
  "stack": "Error: The method \"wallet_invokeKeyring\" does not exist / is not available.\n    at new EthereumRpcError (chrome-extension://efbkfocmmhmpdmiimgpcdpmjkmbaflcb/common-4.js:25949:9)\n    at getEthJsonRpcError (chrome-extension://efbkfocmmhmpdmiimgpcdpmjkmbaflcb/common-4.js:26241:12)\n    at Object.methodNotFound (chrome-extension://efbkfocmmhmpdmiimgpcdpmjkmbaflcb/common-4.js:26147:34)\n    at methodNotFound (chrome-extension://efbkfocmmhmpdmiimgpcdpmjkmbaflcb/common-1.js:25233:43)\n    at PermissionController.getTypedPermissionSpecification (chrome-extension://efbkfocmmhmpdmiimgpcdpmjkmbaflcb/common-1.js:23981:43)\n    at PermissionController.getRestrictedMethod (chrome-extension://efbkfocmmhmpdmiimgpcdpmjkmbaflcb/common-1.js:24005:21)\n    at PermissionController.<anonymous> (chrome-extension://efbkfocmmhmpdmiimgpcdpmjkmbaflcb/common-1.js:25509:42)\n    at Generator.next (<anonymous>)\n    at chrome-extension://efbkfocmmhmpdmiimgpcdpmjkmbaflcb/common-1.js:25467:71\n    at new Promise (<anonymous>)"
}
  at new EthereumRpcError (chrome-extension://efbkfocmmhmpdmiimgpcdpmjkmbaflcb/common-4.js:25949:9)
  at getEthJsonRpcError (chrome-extension://efbkfocmmhmpdmiimgpcdpmjkmbaflcb/common-4.js:26241:12)
  at Object.methodNotFound (chrome-extension://efbkfocmmhmpdmiimgpcdpmjkmbaflcb/common-4.js:26147:34)
  at methodNotFound (chrome-extension://efbkfocmmhmpdmiimgpcdpmjkmbaflcb/common-1.js:25233:43)
  at PermissionController.getTypedPermissionSpecification (chrome-extension://efbkfocmmhmpdmiimgpcdpmjkmbaflcb/common-1.js:23981:43)
  at PermissionController.getRestrictedMethod (chrome-extension://efbkfocmmhmpdmiimgpcdpmjkmbaflcb/common-1.js:24005:21)
  at PermissionController.<anonymous> (chrome-extension://efbkfocmmhmpdmiimgpcdpmjkmbaflcb/common-1.js:25509:42)
  at Generator.next (<anonymous>)
  at chrome-extension://efbkfocmmhmpdmiimgpcdpmjkmbaflcb/common-1.js:25467:71
  at new Promise (<anonymous>)
```

packages

   "@metamask/keyring-api": "^3.0.0",
    "@metamask/snaps-sdk": "^1.4.0",

**Comment by danroc** [comment]
Hey @livingrockrises , what version of the extension you are using?

**Comment by FrederikBolding** [comment]
This was resolved outside of this convo by updating the extension.
