### ISSUE TITLE
Support interactive UI in the simulator

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps#2387]
The simulator still crashes when you try to use interactive UI in a handler:
```
        "stack": "TypeError: i is not a function\n    at https://metamask.github.io/snaps/snaps-simulator/staging/main.js:182:421917\n    at https://metamask.github.io/snaps/snaps-simulator/staging/main.js:182:420311\n    at Object.next (https://metamask.github.io/snaps/snaps-simulator/staging/main.js:182:420416)\n    at u8 (https://metamask.github.io/snaps/snaps-simulator/staging/main.js:182:418769)\n    at a (https://metamask.github.io/snaps/snaps-simulator/staging/main.js:182:422204)\n    at https://metamask.github.io/snaps/snaps-simulator/staging/main.js:182:422265\n    at new Promise (<anonymous>)\n    at n (https://metamask.github.io/snaps/snaps-simulator/staging/main.js:182:422145)\n    at methodImplementation (https://metamask.github.io/snaps/snaps-simulator/staging/main.js:182:422299)\n    at ei._executeRestrictedMethod (https://metamask.github.io/snaps/snaps-simulator/staging/vendor/vendor.js:304:100862)",
        "message": "i is not a function"
```

**Comment by huweihong** [comment]
I also meet this issue.

**Comment by Ebrahim1997r** [comment]
nice
