### ISSUE TITLE
Snaps CLI fails to run in yarn3

### ISSUE THREAD

**Issue by ritave** [MetaMask/snaps#510]
Reproduction
```bash
mkdir tmp
cd tmp
yarn init
# {
#   name: 'tmp',
#   packageManager: 'yarn@3.2.1'
# }
yarn add @metamask/snaps-cli
yarn mm-snaps
```

Stacktrace:
```
<redacted>/tmp/.pnp.cjs:18213
      Error.captureStackTrace(firstError);
            ^

Error: ethjs-query tried to access babel-runtime, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: babel-runtime (via "babel-runtime/regenerator")
Required by: ethjs-query@npm:0.3.7 (via <redacted>/tmp/.yarn/cache/ethjs-query-npm-0.3.7-1f2f795423-08e8fcced0.zip/node_modules/ethjs-query/lib/)

Require stack:
- <redacted>/tmp/.yarn/cache/ethjs-query-npm-0.3.7-1f2f795423-08e8fcced0.zip/node_modules/ethjs-query/lib/index.js
-<redacted>/tmp/.yarn/cache/ethjs-npm-0.3.9-c636c93afa-aa4e69ce4b.zip/node_modules/ethjs/lib/index.js
-<redacted>/tmp/.yarn/cache/eth-method-registry-npm-1.1.0-a722d4cca9-3529e06e67.zip/node_modules/eth-method-registry/index.js
- <redacted>/tmp/.yarn/cache/@metamask-controllers-npm-29.0.1-a74877f8f6-05d3f178c9.zip/node_modules/@metamask/controllers/dist/transaction/TransactionController.js
- <redacted>/tmp/.yarn/cache/@metamask-controllers-npm-29.0.1-a74877f8f6-05d3f178c9.zip/node_modules/@metamask/controllers/dist/index.js
- <redacted>/tmp/.yarn/cache/@metamask-snap-controllers-npm-0.15.0-c31eea8e50-dcfa5e6350.zip/node_modules/@metamask/snap-controllers/dist/snaps/SnapController.js
- <redacted>/tmp/.yarn/cache/@metamask-snap-controllers-npm-0.15.0-c31eea8e50-dcfa5e6350.zip/node_modules/@metamask/snap-controllers/dist/snaps/index.js
- <redacted>/tmp/.yarn/cache/@metamask-snap-controllers-npm-0.15.0-c31eea8e50-dcfa5e6350.zip/node_modules/@metamask/snap-controllers/dist/index.js
- <redacted>/tmp/.yarn/cache/@metamask-snaps-cli-npm-0.15.0-47090ccac6-ef152e1bbd.zip/node_modules/@metamask/snaps-cli/dist/cmds/init/initHandler.js
- <redacted>/tmp/.yarn/cache/@metamask-snaps-cli-npm-0.15.0-47090ccac6-ef152e1bbd.zip/node_modules/@metamask/snaps-cli/dist/cmds/init/index.js
- <redacted>/tmp/.yarn/cache/@metamask-snaps-cli-npm-0.15.0-47090ccac6-ef152e1bbd.zip/node_modules/@metamask/snaps-cli/dist/cmds/index.js
- <redacted>tmp/.yarn/cache/@metamask-snaps-cli-npm-0.15.0-47090ccac6-ef152e1bbd.zip/node_modules/@metamask/snaps-cli/dist/main.js
    at require$$0.Module._resolveFilename (<redacted>/tmp/.pnp.cjs:18213:13)
    at require$$0.Module._load (<redacted>/tmp/.pnp.cjs:18067:42)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (<redacted>/tmp/.yarn/cache/ethjs-query-npm-0.3.7-1f2f795423-08e8fcced0.zip/node_modules/ethjs-query/lib/index.js:3:20)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at require$$0.Module._extensions..js (<redacted>/tmp/.pnp.cjs:18257:33)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at require$$0.Module._load (<redacted>/tmp/.pnp.cjs:18097:14)

Node.js v18.2.0
```

**Comment by FrederikBolding** [comment]
This happens because of very old `Ethjs` dependencies that try to import Babel runtime dependencies but don't actually have them as dependencies. This will be solved once `@metamask/controllers` moves away from `Ethjs` which is an ongoing effort. 

This only happens when using [Yarn 3 PnP](https://yarnpkg.com/features/pnp), so one workaround is to add the following to the `.yarnrc.yml`:

```
nodeLinker: node-modules
```

**Comment by FrederikBolding** [comment]
This may also be solved by `@metamask/controllers` becoming a monorepo with multiple packages for each feature, since `snaps-skunkworks` don't need to import the specific modules that are currently failing.
